services:
  - type: web
    name: grip-backend
    env: python
    rootDir: Backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: grip-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: GRIP_SECRET
        generateValue: true
      - key: ENVIRONMENT
        value: production
    plan: free

databases:
  - name: grip-db
    databaseName: grip
    user: grip
    plan: free
    region: singapore # Optional
